spring:
  application:
    name: game-simulator
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: game-sim
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

application:
  kafka:
    topics:
      test: test

